CREATE PROCEDURE IN_COURSE 
@NOMBRE VARCHAR(MAX), @CREDITOS INT
AS 
DECLARE @ID INT
BEGIN
IF NOT EXISTS (SELECT Name FROM practica1.Course WHERE Name=@NOMBRE)
	BEGIN
		SET @ID=(SELECT LEFT(ABS(CHECKSUM(NEWID())),3));
		BEGIN TRANSACTION
		BEGIN TRY
			INSERT INTO practica1.Course(CodCourse,CreditsRequired,Name) VALUES(@ID,@CREDITOS,@NOMBRE);
			PRINT 'CURSO AGREGADO CORRECTAMENTE'
			COMMIT TRANSACTION

		END TRY
		BEGIN CATCH
			PRINT 'NO SE AGREGO '
			ROLLBACK TRANSACTION

		END CATCH

	END;
ELSE
	PRINT 'YA EXISTE UN CURSO CON ESE NOMBRE'

END;
GO