ALTER TABLE BD2.PRACTICA1.USUARIOS ADD CONSTRAINT CHK_DATA CHECK(Firstname LIKE '%[^0-9]%' and Lastname LIKE '%[^0-9]%');
ALTER TABLE PRACTICA1.COURSE ADD CONSTRAINT CHK_NAME CHECK(NAME  LIKE '%[^0-9]%');
ALTER TABLE BD2.PRACTICA1.COURSE ADD CONSTRAINT CHK_CREDITS CHECK(CREDITSREQUIRED NOT LIKE '%[^0-9]%');
